image: node:4.6.0
before_script:
  - apt-get -qq update
  - apt-get -qq install -y python2.7 python2.7-dev build-essential make gcc g++ libicu-dev nodejs npm nodejs-dev 
  - npm -g install npm --silent  
  
stages:
  - test
  - build
  - clean_up

run_tests:
  stage: test
  script:    
    - npm i -g karma-cli
    - npm i -g gulp
    - npm -g install phantomjs-prebuilt
    - npm install
    - gulp images
    - npm test

build_and_deploy_prod:
  stage: build
  script:
    - rm -rf node_modules

clean_up_job:
  stage: clean_up
  script:
    - rm -rf node_modules
  when: on_failure
    